######################################################################
# Automatically generated by qmake (3.0) Fri Aug 17 14:09:45 2018
######################################################################

TEMPLATE = app
TARGET = Burro
INCLUDEPATH += .

QT += gui widgets

# Input
HEADERS += dcMainWindow.h DocCell.h ImpBox.h
SOURCES += dcMainWindow.cpp DocCell.cpp ImpBox.cpp Burro.C
CONFIG += c++11
